# Generated by Django 6.0.3 on 2026-03-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='chambermembership',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='membershipuserpromo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='membershipuserpromo',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='membershipuserpromo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='category',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='user',
        ),
        migrations.RemoveField(
            model_name='professionallike',
            name='chamber',
        ),
        migrations.RemoveField(
            model_name='professionallike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='work_offer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_chamber',
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='ChamberMembership',
        ),
        migrations.DeleteModel(
            name='MembershipUserPromo',
        ),
        migrations.DeleteModel(
            name='Professional',
        ),
        migrations.DeleteModel(
            name='ProfessionalLike',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
