# Generated by Django 3.0.6 on 2020-05-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0007_subcategory_keywords'),
        ('userinfo', '0007_auto_20200521_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='baseinfo.SubCategory'),
        ),
    ]
