# Generated by Django 3.0.6 on 2020-05-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0007_subcategory_keywords'),
        ('userinfo', '0008_professional_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='category',
            field=models.ManyToManyField(blank=True, to='baseinfo.SubCategory'),
        ),
    ]
