# Generated by Django 3.0.6 on 2020-05-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0009_auto_20200522_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
