# Generated by Django 3.0.6 on 2020-05-23 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0010_workexperience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
