# Generated by Django 3.0.6 on 2020-05-23 02:39

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('userinfo', 'professional')
    for row in Professional.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0011_professional_uuid'),
    ]

    operations = [
    ]
