# Generated by Django 3.0.6 on 2020-05-23 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0012_auto_20200523_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
