# Generated by Django 3.0.6 on 2020-05-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0007_subcategory_keywords'),
        ('userinfo', '0013_auto_20200523_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Province'),
        ),
    ]
