# Generated by Django 3.0.6 on 2020-05-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0014_auto_20200524_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
