# Generated by Django 3.0.6 on 2020-05-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0015_auto_20200525_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_chamber',
            field=models.BooleanField(default=False),
        ),
    ]
