# Generated by Django 3.0.6 on 2020-05-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0016_profile_is_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('06', 'RUC'), ('01', 'DNI'), ('04', 'CE'), ('07', 'Pasaporte')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'Femenino'), ('1', 'Masculino')], max_length=1, null=True),
        ),
    ]
