# Generated by Django 3.0.6 on 2020-05-31 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0007_subcategory_keywords'),
        ('userinfo', '0017_auto_20200530_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.District'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Province'),
        ),
    ]
