# Generated by Django 3.0.6 on 2020-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0019_auto_20200531_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='tarif_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='professional',
            name='tarif_to',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
