# Generated by Django 3.0.6 on 2020-05-31 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0009_auto_20200531_1304'),
        ('userinfo', '0020_auto_20200531_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Country'),
        ),
    ]
