# Generated by Django 3.0.7 on 2020-06-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0021_profile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'Femenino'), ('1', 'Masculino'), ('2', 'No especifica')], max_length=1, null=True),
        ),
    ]
