# Generated by Django 3.1.2 on 2020-10-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0025_emailpasswordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpasswordreset',
            name='token1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='emailpasswordreset',
            name='token2',
            field=models.CharField(max_length=500),
        ),
    ]
