# Generated by Django 3.1.2 on 2020-10-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0026_auto_20201021_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailpasswordreset',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
