# Generated by Django 3.1.2 on 2020-10-25 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0013_auto_20201025_1512'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userinfo', '0027_emailpasswordreset_expire_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.membershippromocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('user', 'promo')},
            },
        ),
    ]
