# Generated by Django 3.1.2 on 2020-10-25 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseinfo', '0013_auto_20201025_1512'),
        ('userinfo', '0028_userpromocode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPromoCode',
            new_name='MembershipUserPromo',
        ),
        migrations.AlterField(
            model_name='membershipuserpromo',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.membershippromocode'),
        ),
    ]
