# Generated by Django 3.1.2 on 2020-11-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0031_socialauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialauth',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='socialauth',
            name='id_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialauth',
            name='social_id',
            field=models.TextField(),
        ),
    ]
