# Generated by Django 3.1.2 on 2020-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0032_auto_20201127_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialauth',
            name='uid',
            field=models.TextField(null=True),
        ),
    ]
