# Generated by Django 3.1.2 on 2021-02-01 22:15

from django.db import migrations
from django.conf import settings

# def make_notifications(apps, schema_editor):
#     User = apps.get_model(settings.AUTH_USER_MODEL)
#     Notification = apps.get_model('userinfo', 'notification')
#     notifications = [Notification(user=user) for user in User.objects.filter(notification=None)]
#     Notification.objects.bulk_create(notifications)

class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0033_socialauth_uid'),
    ]

    # operations = [
    #     migrations.RunPython(make_notifications),
    # ]
