# Generated by Django 3.1.2 on 2021-02-01 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def make_notifications(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Notification = apps.get_model('userinfo', 'notification')
    notifications = [Notification(user=user) for user in User.objects.filter(notification=None)]
    Notification.objects.bulk_create(notifications)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userinfo', '0034_auto_20210201_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_offer', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(make_notifications),
    ]
