# Generated by Django 3.1.2 on 2021-03-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0014_auto_20201210_1226'),
        ('userinfo', '0035_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='street',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profcountry', to='baseinfo.country'),
        ),
    ]
