# Generated by Django 3.1.2 on 2021-03-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0036_auto_20210331_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
