# Generated by Django 3.1.2 on 2021-04-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0037_auto_20210331_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='paypal',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
