# Generated by Django 3.0.8 on 2020-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('document_type', models.CharField(choices=[('06', 'RUC'), ('01', 'DNI'), ('04', 'CE'), ('07', 'Pasaporte')], max_length=2)),
                ('document', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('attorney', models.CharField(max_length=500)),
                ('is_service', models.BooleanField(default=True)),
                ('service_description', models.TextField()),
                ('is_claim', models.BooleanField(default=True)),
                ('claim_description', models.TextField()),
                ('accept_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('01', 'Abierto'), ('02', 'Respondido'), ('03', 'Resuelto')], max_length=2)),
            ],
        ),
    ]
