# Generated by Django 3.0.8 on 2020-08-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintbook',
            name='gtoken',
            field=models.BooleanField(default=False),
        ),
    ]
