# Generated by Django 3.0.8 on 2020-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_complaintbook_gtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintbook',
            name='attorney',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
