# Generated by Django 3.1.2 on 2020-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_auto_20200902_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintbook',
            name='status',
            field=models.CharField(choices=[('01', 'Abierto'), ('02', 'Respondido'), ('03', 'Resuelto')], default='01', max_length=2),
        ),
    ]
