# Generated by Django 3.0.7 on 2020-06-29 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0012_auto_20200628_1914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('amount_refunded', models.IntegerField()),
                ('installments', models.IntegerField()),
                ('installments_amount', models.IntegerField()),
                ('currency_code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('card_email', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=100)),
                ('last_four', models.CharField(max_length=4)),
                ('iin_bin', models.CharField(max_length=200)),
                ('iin_card_brand', models.CharField(max_length=200)),
                ('iin_card_type', models.CharField(max_length=200)),
                ('iin_issuer_name', models.CharField(max_length=200)),
                ('iin_issuer_country', models.CharField(max_length=200)),
                ('client_ip', models.CharField(max_length=200)),
                ('client_ip_country', models.CharField(max_length=200)),
                ('client_browser', models.CharField(max_length=200)),
                ('client_device_fingerprint', models.CharField(max_length=500)),
                ('client_device_type', models.CharField(max_length=300)),
                ('outcome_type', models.CharField(max_length=400)),
                ('outcome_code', models.CharField(max_length=400)),
                ('ourcome_merchant_message', models.TextField()),
                ('ourcome_user_message', models.TextField()),
                ('capture', models.BooleanField()),
                ('reference_code', models.CharField(max_length=300)),
                ('authorization_code', models.CharField(max_length=300)),
                ('variable_fee', models.IntegerField()),
                ('fixed_fee', models.IntegerField()),
                ('total_fee', models.IntegerField()),
                ('total_fee_taxes', models.IntegerField()),
                ('transfer_amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='work.Quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
