# Generated by Django 3.0.7 on 2020-06-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20200628_1914'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work.Quote'),
        ),
    ]
