# Generated by Django 6.0.3 on 2026-03-18 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberincome',
            name='cw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='work.contractedwork'),
        ),
        migrations.AddField(
            model_name='chamberincome',
            name='payed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_income', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work.quote'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmp',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work.quote'),
        ),
        migrations.AddField(
            model_name='paymentmp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentpaypal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymentmp'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='paypal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymentpaypal'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='work.quote'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
