# Generated by Django 3.0.7 on 2020-06-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_active',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
