# Generated by Django 3.0.7 on 2020-06-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_card_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client_browser',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client_device_fingerprint',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client_device_type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
