# Generated by Django 3.0.8 on 2020-07-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200630_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-id']},
        ),
    ]
