# Generated by Django 3.0.8 on 2020-08-13 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0021_auto_20200812_1439'),
        ('baseinfo', '0009_auto_20200531_1304'),
        ('payment', '0005_auto_20200705_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Procesando pago'), ('1', 'Pagado')], default='0', max_length=1)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('operation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_from', models.CharField(blank=True, max_length=50, null=True)),
                ('acccount_to', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_igv', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_from', to='baseinfo.Bank')),
                ('bank_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_to', to='baseinfo.Bank')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamber_income', to=settings.AUTH_USER_MODEL)),
                ('cw', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.ContractedWork')),
            ],
        ),
    ]
