# Generated by Django 3.0.8 on 2020-08-13 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_auto_20200812_1439'),
        ('payment', '0006_chamberincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamberincome',
            name='cw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='work.ContractedWork'),
        ),
    ]
