# Generated by Django 3.0.8 on 2020-08-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200813_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamberincome',
            options={'ordering': ['-id']},
        ),
    ]
