# Generated by Django 3.0.8 on 2020-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20200913_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmp',
            name='sponsor_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
