# Generated by Django 3.0.8 on 2020-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20200913_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmp',
            name='card_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
