# Generated by Django 3.1.2 on 2020-12-02 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0012_auto_20200913_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberincome',
            name='payed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_income', to=settings.AUTH_USER_MODEL),
        ),
    ]
