# Generated by Django 3.1.2 on 2021-03-03 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0013_chamberincome_payed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymentmp'),
        ),
        migrations.CreateModel(
            name='PaymentPaypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=300)),
                ('intent', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('payer_email_address', models.CharField(max_length=300)),
                ('payer_payer_id', models.CharField(max_length=300)),
                ('payer_address', models.CharField(max_length=300)),
                ('payer_name', models.CharField(max_length=300)),
                ('payer_surname', models.CharField(max_length=300)),
                ('purchase_description', models.CharField(max_length=300)),
                ('purchase_reference_id', models.CharField(max_length=300)),
                ('purchase_amount', models.CharField(max_length=300)),
                ('purchase_currency', models.CharField(max_length=300)),
                ('purchase_email_address', models.CharField(max_length=300)),
                ('purchase_merchant_id', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='paypal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.paymentpaypal'),
        ),
    ]
