# Generated by Django 3.1.2 on 2021-04-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20210303_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpaypal',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
