# Generated by Django 3.1.2 on 2021-04-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_paymentpaypal_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberincome',
            name='paypal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
