# Generated by Django 6.0.3 on 2026-03-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippromocode',
            name='for_chamber',
        ),
    ]
