# Generated by Django 3.0.5 on 2020-05-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_auto_20200510_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.RemoveField(
            model_name='province',
            name='iso3166_2',
        ),
        migrations.AddField(
            model_name='province',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Department'),
        ),
    ]
