# Generated by Django 3.0.5 on 2020-05-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0003_auto_20200510_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='Department',
            new_name='department',
        ),
    ]
