# Generated by Django 3.0.5 on 2020-05-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_auto_20200510_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='baseinfo.Country'),
        ),
        migrations.AlterField(
            model_name='province',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='baseinfo.Department'),
        ),
    ]
