# Generated by Django 3.0.6 on 2020-05-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0006_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
