# Generated by Django 3.0.6 on 2020-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0007_subcategory_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3166',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
