# Generated by Django 3.0.6 on 2020-05-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0008_auto_20200531_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
