# Generated by Django 3.0.6 on 2020-06-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='req_hous',
            new_name='req_hours',
        ),
    ]
