# Generated by Django 3.0.7 on 2020-06-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200601_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='quotereply',
            options={'ordering': ['-id']},
        ),
    ]
