# Generated by Django 3.0.7 on 2020-06-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20200606_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotereply',
            old_name='is_chamber',
            new_name='is_client',
        ),
        migrations.RenameField(
            model_name='quotereply',
            old_name='reply',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='quotereply',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Quote'),
        ),
    ]
