# Generated by Django 3.0.7 on 2020-06-07 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0004_auto_20200606_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotereply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qreply_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
