# Generated by Django 3.0.7 on 2020-06-07 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20200606_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='job_description',
        ),
    ]
