# Generated by Django 3.0.7 on 2020-06-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_remove_quote_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotereply',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='quotereply',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='quotereply',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='quotereply',
            name='status',
        ),
        migrations.AddField(
            model_name='quote',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.CancelReason'),
        ),
        migrations.AddField(
            model_name='quote',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='job_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('0', 'Nuevo'), ('1', 'Visto'), ('2', 'Negociado'), ('3', 'Aceptado'), ('4', 'Rechazado Chamber'), ('5', 'Rechazado Cliente')], default='0', max_length=1),
        ),
    ]
