# Generated by Django 3.0.7 on 2020-06-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20200606_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Visto'), ('2', 'Negociado'), ('3', 'Aceptado'), ('4', 'Rechazado por Chamber'), ('5', 'Rechazado por Cliente')], default='0', max_length=1),
        ),
    ]
