# Generated by Django 3.0.7 on 2020-06-25 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseinfo', '0009_auto_20200531_1304'),
        ('work', '0008_auto_20200608_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelreason',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Visto'), ('2', 'Cotizado'), ('3', 'Aceptado'), ('4', 'Cancelado por Chamber'), ('5', 'Cancelado por Cliente'), ('6', 'Requiere mas Info.')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='WorkOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid1', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.TextField(default='')),
                ('expire_date', models.DateField()),
                ('flexible_time', models.BooleanField(default=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('say_price', models.BooleanField(default=True)),
                ('tarif_from', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarif_to', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('req_hours', models.BooleanField(default=False)),
                ('hours', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('0', 'Nueva'), ('1', 'Vencida'), ('2', 'Cancelada'), ('3', 'Finalizada')], default='0', max_length=1)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('remote_work', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('cancel_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.CancelReason')),
                ('category', models.ManyToManyField(blank=True, to='baseinfo.SubCategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='baseinfo.Department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='baseinfo.District')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='baseinfo.Province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
