# Generated by Django 3.0.7 on 2020-06-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20200625_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffer',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
