# Generated by Django 3.0.7 on 2020-06-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_workoffer_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoffer',
            options={'ordering': ['-id']},
        ),
    ]
