# Generated by Django 3.0.8 on 2020-07-05 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0012_auto_20200628_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoffer',
            name='status',
            field=models.CharField(choices=[('0', 'Vacante'), ('1', 'Vencida'), ('2', 'Cancelada'), ('3', 'Finalizada')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='WorkOfferCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('message', models.TextField()),
                ('customer_accepted', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.WorkOffer')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('work_offer', 'chamber')},
            },
        ),
    ]
