# Generated by Django 3.0.8 on 2020-07-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20200705_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffercandidate',
            name='canceled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoffercandidate',
            name='how_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoffercandidate',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
