# Generated by Django 3.0.8 on 2020-07-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_auto_20200711_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffercandidate',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
