# Generated by Django 3.0.8 on 2020-07-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_workoffercandidate_accepted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoffercandidate',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
