# Generated by Django 3.0.8 on 2020-07-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_auto_20200712_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractedwork',
            name='status',
            field=models.CharField(choices=[('0', 'Vacante'), ('1', 'Vencida'), ('2', 'Cancelada'), ('3', 'Finalizada')], default='0', max_length=1),
        ),
    ]
