# Generated by Django 3.0.8 on 2020-07-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_contractedwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contractedwork',
            name='status',
            field=models.CharField(choices=[('0', 'En proceso'), ('1', 'Finalizado'), ('2', 'Conforme'), ('3', 'Cancelado')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='status',
            field=models.CharField(choices=[('0', 'En proceso'), ('1', 'Finalizado'), ('2', 'Conforme'), ('3', 'Cancelado')], default='0', max_length=1),
        ),
    ]
