# Generated by Django 3.0.8 on 2020-08-12 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0020_auto_20200717_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractedwork',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='cwmessage',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='contractedwork',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractedwork',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cwreview',
            name='chamber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamber_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractedwork',
            name='status',
            field=models.CharField(choices=[('0', 'En proceso'), ('1', 'Finalizado'), ('2', 'Finalizado por Chamber'), ('4', 'Cancelado por Chamber'), ('5', 'Cancelado por Cliente')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='cwreview',
            name='cw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.ContractedWork'),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='status',
            field=models.CharField(choices=[('0', 'Por realizar'), ('1', 'Finalizado'), ('2', 'Conforme'), ('3', 'Cancelado')], default='0', max_length=1),
        ),
    ]
