# Generated by Django 3.0.8 on 2020-09-04 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0021_auto_20200812_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_client', models.BooleanField(default=False)),
                ('client_prop', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client_prop_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chamber_prop', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chamber_prop_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.ContractedWork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='how_message',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='DisputeReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_client', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Dispute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
