# Generated by Django 3.0.8 on 2020-09-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0022_auto_20200904_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='chamber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispute_chamber', to=settings.AUTH_USER_MODEL),
        ),
    ]
