# Generated by Django 3.0.8 on 2020-09-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_dispute_chamber'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('0', 'En proceso'), ('1', 'Respuesta del Chamber'), ('2', 'Respuesta del Cliente'), ('4', 'Resuelto'), ('5', 'Cancelada por Cliente')], default=0, max_length=2),
        ),
    ]
