# Generated by Django 3.0.8 on 2020-09-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0024_dispute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractedwork',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.CancelReason'),
        ),
    ]
