# Generated by Django 3.0.8 on 2020-09-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0025_contractedwork_cancel_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispute',
            old_name='client_prop',
            new_name='customer_prop',
        ),
        migrations.RenameField(
            model_name='dispute',
            old_name='client_prop_fee',
            new_name='customer_prop_fee',
        ),
        migrations.RenameField(
            model_name='dispute',
            old_name='is_client',
            new_name='is_customer',
        ),
    ]
