# Generated by Django 3.1.2 on 2020-10-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0026_auto_20200917_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cwreview',
            options={'ordering': ['-id']},
        ),
    ]
