# Generated by Django 3.1.2 on 2020-11-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_auto_20201028_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffercandidate',
            name='info_required',
            field=models.BooleanField(default=False),
        ),
    ]
