# Generated by Django 3.1.2 on 2021-03-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0007_auto_20210303_1527'),
        ('work', '0028_workoffercandidate_info_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_svc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='svc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='svc.svc'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='flexible_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='remote_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='req_hours',
            field=models.BooleanField(default=True),
        ),
    ]
