# Generated by Django 3.1.2 on 2021-03-24 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0029_auto_20210303_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConplainReason',
            new_name='ComplainReason',
        ),
        migrations.AddField(
            model_name='quote',
            name='required_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='revision',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotereply',
            name='required_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotereply',
            name='revision',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
