# Generated by Django 3.1.2 on 2021-03-27 20:01

import adminsite.functions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0030_auto_20210324_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_client', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=adminsite.functions.user_file_path)),
                ('cw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.contractedwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
