# Generated by Django 3.1.2 on 2021-03-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0031_cwfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwfile',
            name='filename',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
