# Generated by Django 3.1.2 on 2021-03-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0032_cwfile_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='service_date',
        ),
        migrations.AddField(
            model_name='quote',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
