# Generated by Django 3.1.2 on 2021-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0033_auto_20210327_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffercandidate',
            name='required_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoffercandidate',
            name='revision',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
