# Generated by Django 3.1.2 on 2021-04-01 17:30

import adminsite.functions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0034_auto_20210329_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_client', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=adminsite.functions.user_file_path)),
                ('filename', models.CharField(blank=True, max_length=300, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CWFile',
        ),
    ]
