# Generated by Django 3.1.2 on 2021-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0035_auto_20210401_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
