# Generated by Django 6.0.3 on 2026-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanvst', '0002_add_direct_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='directtip',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directtip',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
