# Generated by Django 6.0.3 on 2026-03-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanvst', '0004_campaign_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='soundcloud',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='spotify',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
