# Generated by Django 3.1.2 on 2021-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svsopt',
            name='includes',
            field=models.ManyToManyField(blank=True, to='svc.SvcIncluide'),
        ),
    ]
