# Generated by Django 3.1.2 on 2021-02-23 22:14

import adminsite.functions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('svc', '0002_auto_20210223_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svc',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='svsopt',
            options={'ordering': ['svc', 'level']},
        ),
        migrations.AddField(
            model_name='svsopt',
            name='level',
            field=models.CharField(choices=[('0', 'Basic'), ('1', 'Standard'), ('2', 'Pro')], default='0', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='svsopt',
            unique_together={('svc', 'level')},
        ),
        migrations.CreateModel(
            name='SvcImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=adminsite.functions.user_image_path)),
                ('svc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svc.svc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
