# Generated by Django 3.1.2 on 2021-02-23 22:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0014_auto_20201210_1226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('svc', '0003_auto_20210223_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SvcIncluide',
            new_name='SvcInclude',
        ),
    ]
