# Generated by Django 3.1.2 on 2021-02-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0004_auto_20210223_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svcimage',
            name='svc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svcimage', to='svc.svc'),
        ),
    ]
