# Generated by Django 3.1.2 on 2021-02-24 21:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('svc', '0005_auto_20210224_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SvsOpt',
            new_name='SvcOpt',
        ),
    ]
