# Generated by Django 3.1.2 on 2021-03-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0006_auto_20210224_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svcopt',
            name='svc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svcopt', to='svc.svc'),
        ),
    ]
