# Generated by Django 3.1.2 on 2021-03-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0008_auto_20210310_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='svc',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
