# Generated by Django 3.1.2 on 2021-03-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0014_auto_20201210_1226'),
        ('svc', '0009_svc_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='svc',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='baseinfo.subcategory'),
        ),
    ]
