# Generated by Django 3.1.2 on 2021-03-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0010_svc_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svc',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
