# Generated by Django 6.0.3 on 2026-03-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0011_auto_20210324_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='svcimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='svcinclude',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='svcopt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
