# Generated by Django 6.0.3 on 2026-03-19 13:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearing_days_default', models.PositiveIntegerField(default=14, help_text='Días antes de que los fondos estén disponibles para retirar (default global).')),
                ('min_payout_usd', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Monto mínimo en USD para solicitar un payout.', max_digits=10)),
                ('auto_payout_day', models.PositiveIntegerField(default=1, help_text='Día del mes en que se ejecutan los auto-payouts (1–28).')),
            ],
            options={
                'verbose_name': 'Wallet Configuration',
                'verbose_name_plural': 'Wallet Configuration',
            },
        ),
        migrations.CreateModel(
            name='ArtistWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('PEN', 'Peruvian Sol'), ('MXN', 'Mexican Peso'), ('COP', 'Colombian Peso'), ('ARS', 'Argentine Peso'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso')], default='USD', max_length=3)),
                ('balance_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fondos disponibles para retirar ahora.', max_digits=12)),
                ('balance_pending', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fondos en período de clearing, aún no retirables.', max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total acumulado histórico (neto después de fees).', max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total retirado históricamente.', max_digits=12)),
                ('clearing_days', models.PositiveIntegerField(blank=True, help_text='Override del período de clearing para este artista. Dejar vacío para usar el valor global.', null=True)),
                ('auto_payout_enabled', models.BooleanField(default=False)),
                ('auto_payout_threshold', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Balance mínimo requerido para disparar el auto-payout mensual.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artist Wallet',
                'verbose_name_plural': 'Artist Wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('category', models.CharField(choices=[('MEMBERSHIP_INCOME', 'Membership Income'), ('FAN_FUNDING', 'Fan Funding'), ('CONTENT_SALE', 'Content Sale'), ('PLATFORM_FEE', 'Platform Fee'), ('PAYOUT', 'Payout'), ('REFUND', 'Refund'), ('CHARGEBACK', 'Chargeback'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('PEN', 'Peruvian Sol'), ('MXN', 'Mexican Peso'), ('COP', 'Colombian Peso'), ('ARS', 'Argentine Peso'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso')], default='USD', max_length=3)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Monto bruto (lo que pagó el fan).', max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee de la plataforma descontado al ingreso.', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto neto acreditado al artista (gross - fee).', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (in clearing)'), ('CLEARED', 'Cleared (available)'), ('COMPLETED', 'Completed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=10)),
                ('available_at', models.DateTimeField(blank=True, help_text='Fecha/hora en que los fondos estarán disponibles para retirar.', null=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.artistwallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'status'], name='wallet_wall_wallet__235478_idx'), models.Index(fields=['status', 'available_at'], name='wallet_wall_status_4b836a_idx')],
            },
        ),
    ]
