# Generated by Django 6.0.3 on 2026-03-19 13:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('PEN', 'Peruvian Sol'), ('MXN', 'Mexican Peso'), ('COP', 'Colombian Peso'), ('ARS', 'Argentine Peso'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso')], max_length=3)),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Monto solicitado por el artista.', max_digits=12)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee de la transferencia bancaria/proveedor.', max_digits=10)),
                ('amount_to_transfer', models.DecimalField(decimal_places=2, help_text='Monto que efectivamente recibirá el artista (amount_requested - transfer_fee).', max_digits=12)),
                ('provider', models.CharField(choices=[('MERCADOPAGO', 'MercadoPago'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=15)),
                ('provider_account_ref', models.CharField(blank=True, help_text='Email PayPal, cuenta MercadoPago, etc.', max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (awaiting admin approval)'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('is_automatic', models.BooleanField(default=False, help_text='True si fue generado por el auto-payout mensual.')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, help_text='ID externo de la transferencia (proveedor de pagos).', max_length=300)),
                ('failure_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Cuenta bancaria destino (solo para Bank Transfer).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='userinfo.bankaccount')),
                ('wallet_transaction', models.OneToOneField(help_text='Transacción DEBIT que reserva los fondos.', on_delete=django.db.models.deletion.PROTECT, related_name='payout_request', to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['artist', 'status'], name='wallet_payo_artist__751908_idx'), models.Index(fields=['status', 'requested_at'], name='wallet_payo_status_e5c474_idx')],
            },
        ),
    ]
