# Generated by Django 6.0.3 on 2026-03-22 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wallet', '0002_payoutrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DlocalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlocal_payment_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('PEN', 'Peruvian Sol'), ('MXN', 'Mexican Peso'), ('COP', 'Colombian Peso'), ('ARS', 'Argentine Peso'), ('BRL', 'Brazilian Real'), ('CLP', 'Chilean Peso')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference_id', models.PositiveIntegerField()),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'dLocal Payment',
                'verbose_name_plural': 'dLocal Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
